# Generated by Django 3.2 on 2021-04-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
