# Generated by Django 3.2 on 2021-04-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0002_comment_commenter_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter_email',
        ),
    ]
