# Generated by Django 3.2 on 2021-04-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0002_alter_userprofile_name'),
        ('uav', '0003_remove_comment_commenter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='micro.userprofile'),
        ),
    ]
