# Generated by Django 3.2 on 2021-04-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0004_auto_20210417_1627'),
        ('uav', '0006_uavvideo'),
    ]

    operations = [
    ]
