# Generated by Django 3.2 on 2021-04-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(choices=[('user', 'user'), ('customer', 'customer'), ('staff', 'staff')], default='user', max_length=10)),
                ('email', models.EmailField(max_length=250)),
                ('profile_photo', models.ImageField(default='default_img/default-avatar.png', upload_to='profiles/')),
                ('bio', models.TextField(max_length=1000)),
                ('background', models.ImageField(default='default_img/bg8.jpg', upload_to='user_backgrounds/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
