# Generated by Django 3.2 on 2021-04-18 08:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=250),
        ),
    ]
