# Generated by Django 3.2 on 2021-04-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixedwing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='RCReceiver',
            new_name='RC_Receiver',
        ),
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='RCTransmitter',
            new_name='RC_Transmitter',
        ),
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='averageChordInMm',
            new_name='average_Chord_in_mm',
        ),
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='brushlessMotor',
            new_name='brushless_Motor',
        ),
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='cruiseSpeedInMPerS',
            new_name='cruise_Speed_in_mtr_per_s',
        ),
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='electronicSpeedContorller',
            new_name='electronic_Speed_Contorller',
        ),
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='inertialMeasurementUnit',
            new_name='inertial_Measurement_Unit',
        ),
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='weightIn_grams',
            new_name='weight_in_grams',
        ),
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='wingAreaInMm2',
            new_name='wing_Area_in_mm2',
        ),
        migrations.RenameField(
            model_name='fixedwingpost',
            old_name='wingSpanInMm',
            new_name='wing_Span_in_mm',
        ),
    ]
