# Generated by Django 3.2 on 2021-04-21 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixedwing', '0003_remove_fixedwingpost_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedwingpost',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
