# Generated by Django 3.2 on 2021-04-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixedwing', '0004_fixedwingpost_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedwingpost',
            name='user_name',
        ),
    ]
