# Generated by Django 3.2 on 2021-04-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=500)),
            ],
        ),
    ]
