# Generated by Django 3.2 on 2021-04-24 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_learnpoints_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnpoints',
            name='brief_info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
