# Generated by Django 3.2 on 2021-04-24 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_learnpoints_brief_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnpoints',
            name='brief_info',
        ),
        migrations.AddField(
            model_name='training',
            name='brief_info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
