# Generated by Django 3.2 on 2021-04-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=200)),
                ('card_description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('brief_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LearnPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=500)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commercial.commercial')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(null=True, upload_to='videos/')),
                ('video_info', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commercial.commercial')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('image_info', models.CharField(default=None, max_length=300)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commercial.commercial')),
            ],
        ),
    ]
